### ISSUE TITLE
Script compile error

### ISSUE THREAD

**Issue by TML233** [cubeww/UndertaleModTool-ExportToProjectScript#2]
UndertaleModTool version 0.2.0

>(22,5): error CS0103: The name 'ScriptError' does not exist in the current context

After replacing ScriptError method to ScriptMessage and removed its second param "Error". Running it again caused another error:
>(71,8): error CS1061: 'TextureWorker' does not contain a definition for 'Cleanup' and no extension method 'Cleanup' accepting a first argument of type 'TextureWorker' could be found (are you missing a using directive or an assembly reference?).

**Comment by Animeliqite** [comment]
That seems like the owner of this script probably has a different Undertale Mod Tool version. I haven't tried other versions yet, but it might be the solution.

**Comment by cubeww** [comment]
Join UNDERMINERS discord (https://discord.gg/G3z9nYm) to download the latest utmt build :)

**Comment by Animeliqite** [comment]
I'm banned from their server though @cubeww .
Could you give me the latest link of it without being in their server?
