### ISSUE TITLE
Reference from #2 but the latest version of Undertale Mod Tool is needed for banned people of Underminers

### ISSUE THREAD

**Issue by Animeliqite** [cubeww/UndertaleModTool-ExportToProjectScript#4]
I was banned from Underminers server, and that's why I can't download the latest version of Undertale Mod Tool. Could you give us the link of the latest Undertale Mod Tool in the description, or here? You could also put the version of Undertale Mod Tool that you're using on the repository files.

**Comment by cubeww** [comment]
I uploaded the latest build of UTMT in this repo/release, just download it :)

**Comment by Animeliqite** [comment]
Okay, thanks a lot.
