### ISSUE TITLE
Error with running script, see below.

### ISSUE THREAD

**Issue by Username13211** [cubeww/UndertaleModTool-ExportToProjectScript#7]
https://gyazo.com/6a015a306a4b593b8da066a986128af4

**Comment by Username13211** [comment]
Can you please help me with this problem?

**Comment by cubeww** [comment]
I uploaded the latest build of UTMT in this repo/release, just download it :)

**Comment by Username13211** [comment]
> I uploaded the latest build of UTMT in this repo/release, just download it :)

Ok.

**Comment by Username13211** [comment]
> I uploaded the latest build of UTMT in this repo/release, just download it :)

Thank you so much.
